
-- TOTAL LOCATION:

SELECT COUNT(PK_ID_Location)
FROM location

-- TOTAL LOCATION FAIT PAR UN MEMBRE

SELECT COUNT(PK_ID_Location)
FROM location
WHERE PK_ID_Membre=1;


--TOTAL DE FILMS AVEC LE TITRE  TITANIC

SELECT COUNT(PK_ID_Film)
FROM film
WHERE film.titre ="Titanic";


-- NOMBRE DE FOIS QU'UN FILM DONNÉ A ÉTÉ LOUÉ
